export { default as clientsReducer } from './clients.slice';
export { default as invoiceReducer } from './invoice.slice';
export { default as productsReducer } from './products.slice';
export { default as cartReducer } from './cart.slice';
export { default as detailsReducer } from './details.slice';
export * from './invoice.slice';
export * from './clients.slice';
export * from './products.slice';
export * from './cart.slice';
export * from './details.slice';
